"""Builds the JSBSim model files (aircraft, torque-source engine, propeller) for a run.

Every run writes its own copy of the exact XML it flew with into
<run_dir>/jsbsim/, and the SHA-256 of each file goes into the run metadata. That
makes each log traceable to the model that produced it.
"""
from __future__ import annotations

import datetime as _dt
import hashlib
import re
from pathlib import Path
from string import Template

import numpy as np

from . import __version__
from .units import FT, IN, SLUG_FT2

DATA = Path(__file__).parent / "data"

# Engine "power" rating used only to scale the JSBSim throttle so that it acts as a
# torque source (throttle = P_shaft / TORQUE_SOURCE_POWER_W). Not a physical limit;
# physical limits are applied in the motor/ESC/battery models.
TORQUE_SOURCE_POWER_W = 10000.0

# Original Rascal inertia (slug*ft^2) from the ArduPilot/FlightGear model.
BASE_INERTIA = {"ixx": 1.95, "iyy": 1.55, "izz": 1.91}


# --------------------------------------------------------------------------- APC data
def read_apc_per3(path: Path) -> dict[int, np.ndarray]:
    """Parse an APC PER3_*.dat performance file.

    Returns {rpm: array[n, 4]} with columns (J, Ct, Cp, eta). J is recomputed
    from the tabulated airspeed (mph) because the J column is rounded to two
    decimals, which is too coarse at low RPM.
    """
    txt = Path(path).read_text(encoding="utf-8", errors="replace").splitlines()
    diam_m = None
    m = re.search(r"(\d+(?:\.\d+)?)x(\d+(?:\.\d+)?)", txt[0])
    if m:
        diam_m = float(m.group(1)) * IN
    blocks: dict[int, list] = {}
    cur = None
    for line in txt:
        mm = re.search(r"PROP RPM =\s+(\d+)", line)
        if mm:
            cur = int(mm.group(1))
            blocks[cur] = []
            continue
        parts = line.split()
        if cur is not None and len(parts) == 8:
            try:
                v = [float(x) for x in parts]
            except ValueError:
                continue
            v_mps = v[0] * 0.44704
            n = cur / 60.0
            J = v_mps / (n * diam_m) if diam_m else v[1]
            blocks[cur].append([J, v[3], v[4], v[2]])
    return {k: np.asarray(b) for k, b in blocks.items() if len(b) > 3}


def build_prop_tables(apc: dict[int, np.ndarray], j_grid: np.ndarray, j_extrap_max: float = 0.9):
    """Resample APC blocks onto a common J grid.

    Inside the data range: linear interpolation. Beyond the last tabulated J
    (windmilling region, not covered by APC), linear extrapolation using a
    least-squares slope of the last 4 points, up to j_extrap_max; beyond that
    JSBSim holds the end value. Returns (rpms, CT[nJ, nRPM], CP[nJ, nRPM], j_data_max).
    """
    rpms = sorted(apc)
    CT = np.zeros((len(j_grid), len(rpms)))
    CP = np.zeros_like(CT)
    jmax_all = []
    for c, r in enumerate(rpms):
        d = apc[r]
        J, ct, cp = d[:, 0], d[:, 1], d[:, 2]
        jmax = J.max()
        jmax_all.append(jmax)
        sct = np.polyfit(J[-4:], ct[-4:], 1)
        scp = np.polyfit(J[-4:], cp[-4:], 1)
        for i, j in enumerate(j_grid):
            if j <= jmax:
                CT[i, c] = np.interp(j, J, ct)
                CP[i, c] = np.interp(j, J, cp)
            else:
                je = min(j, j_extrap_max)
                CT[i, c] = np.polyval(sct, je)
                CP[i, c] = np.polyval(scp, je)
    return rpms, CT, CP, float(min(jmax_all))


def _table_xml(name: str, j_grid, rpms, M) -> str:
    cols = "".join(f"{r / 1000.0:9.1f}" for r in rpms)
    rows = "\n".join(
        f"      {j:5.3f} " + "".join(f"{M[i, c]:9.5f}" for c in range(len(rpms)))
        for i, j in enumerate(j_grid)
    )
    return (f'  <table name="{name}" type="internal">\n    <tableData>\n'
            f"            {cols}\n{rows}\n    </tableData>\n  </table>\n")


def propeller_xml(cfg_prop: dict) -> tuple[str, dict]:
    """JSBSim propeller file. The 'blade-angle' (pitch) axis of JSBSim's
    variable-pitch table interface is repurposed as propeller speed in kRPM, so
    the tables are CT(J, kRPM) and CP(J, kRPM). The lab writes
    propulsion/engine/blade-angle = RPM/1000 every step (manual-pitch mode:
    JSBSim never changes it on its own)."""
    src = DATA / cfg_prop.get("data_file", "PER3_18x8E.dat")
    apc = read_apc_per3(src)
    j_grid = np.round(np.concatenate([np.arange(0.0, 0.64 + 1e-9, 0.02),
                                      [0.68, 0.72, 0.76, 0.80, 0.90]]), 3)
    rpms, CT, CP, jdmax = build_prop_tables(apc, j_grid)
    diam_in = float(cfg_prop["diameter_in"])
    ixx = float(cfg_prop["inertia_kgm2"]) / SLUG_FT2
    xml = (
        '<?xml version="1.0"?>\n'
        f"<!-- GENERATED by uavlab {__version__}. Source: APC Propellers performance file "
        f"{src.name} (manufacturer-computed data).\n"
        "     Axis 1 (rows) = advance ratio J; axis 2 (columns) = propeller speed in kRPM,\n"
        "     carried through JSBSim's blade-angle property (manual pitch mode).\n"
        f"     Rows with J > {jdmax:.2f} are linear extrapolations (windmilling region). -->\n"
        '<propeller name="lab_propeller">\n'
        f"  <ixx unit=\"SLUG*FT2\"> {ixx:.6f} </ixx>\n"
        f"  <diameter unit=\"IN\"> {diam_in} </diameter>\n"
        "  <numblades> 2 </numblades>\n"
        f"  <minpitch> {rpms[0] / 1000.0} </minpitch>\n"
        f"  <maxpitch> {rpms[-1] / 1000.0} </maxpitch>\n"
        f"  <ct_factor> {float(cfg_prop.get('ct_scale', 1.0))} </ct_factor>\n"
        f"  <cp_factor> {float(cfg_prop.get('cp_scale', 1.0))} </cp_factor>\n"
        + _table_xml("C_THRUST", j_grid, rpms, CT)
        + _table_xml("C_POWER", j_grid, rpms, CP)
        + "</propeller>\n"
    )
    info = {"j_data_max": jdmax, "krpm_min": rpms[0] / 1000.0, "krpm_max": rpms[-1] / 1000.0,
            "source": src.name}
    return xml, info


def engine_xml() -> str:
    return ('<?xml version="1.0"?>\n'
            "<!-- GENERATED by uavlab. Torque source: the lab's motor model sets its power each\n"
            "     step through the throttle (throttle = P_shaft / rating). -->\n"
            '<electric_engine name="lab_motor_torque_source">\n'
            f'  <power unit="WATTS"> {TORQUE_SOURCE_POWER_W} </power>\n'
            "</electric_engine>\n")


def aircraft_xml(cfg: dict, run_id: str = "", config_hash: str = "") -> str:
    ac = cfg["aircraft"]
    bat = cfg["powertrain"]["battery"]
    cal = ac.get("aero_calibration", {})
    isc = float(ac.get("inertia_scale", 1.0))
    base_k = 0.04
    tmpl = Template((DATA / "aircraft" / "rascal110_e.xml.tmpl").read_text(encoding="utf-8"))
    return tmpl.substitute(
        run_id=run_id or "-", config_hash=config_hash or "-",
        date=_dt.date.today().isoformat(), lab_version=__version__,
        ixx=f"{BASE_INERTIA['ixx'] * isc:.4f}", iyy=f"{BASE_INERTIA['iyy'] * isc:.4f}",
        izz=f"{BASE_INERTIA['izz'] * isc:.4f}",
        airframe_mass_kg=f"{float(ac['airframe_mass_kg']):.4f}",
        cg_x_in=f"{float(ac.get('cg_x_in', 36.4)):.3f}",
        battery_mass_kg=f"{float(bat['mass_kg']):.4f}",
        battery_x_in=f"{float(ac.get('battery_x_in', 36.4)):.3f}",
        payload_mass_kg=f"{float(ac.get('payload_mass_kg', 0.0)):.4f}",
        payload_x_in=f"{float(ac.get('payload_x_in', 36.4)):.3f}",
        rolling_friction=f"{float(cfg['mission']['runway'].get('rolling_friction', 0.04)):.4f}",
        tailwheel_steer_deg=f"{float(ac.get('tailwheel_steer_deg', 30.0)):.1f}",
        gear_damping=f"{float(ac.get('gear_damping_lbf_per_fps', 10.0)):.2f}",
        cd0_scale=f"{float(cal.get('cd0_scale', 1.0)):.4f}",
        cdi_scale=f"{float(cal.get('cdi_scale', 1.0)):.4f}",
        cdi_k=f"{base_k * float(cal.get('cdi_scale', 1.0)):.5f}",
        cl_scale=f"{float(cal.get('cl_scale', 1.0)):.4f}",
    )


def sha256(path: Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def build_model_dir(cfg: dict, root: Path, run_id: str = "", config_hash: str = "") -> dict:
    """Write aircraft/engine/propeller XML under root; return paths, hashes, info."""
    root = Path(root)
    (root / "aircraft" / "rascal110_e").mkdir(parents=True, exist_ok=True)
    (root / "engine").mkdir(parents=True, exist_ok=True)
    (root / "systems").mkdir(parents=True, exist_ok=True)
    ac_path = root / "aircraft" / "rascal110_e" / "rascal110_e.xml"
    ac_path.write_text(aircraft_xml(cfg, run_id, config_hash), encoding="utf-8")
    eng_path = root / "engine" / "lab_motor_torque_source.xml"
    eng_path.write_text(engine_xml(), encoding="utf-8")
    prop_txt, prop_info = propeller_xml(cfg["powertrain"]["propeller"])
    prop_path = root / "engine" / "lab_propeller.xml"
    prop_path.write_text(prop_txt, encoding="utf-8")
    files = {"aircraft": ac_path, "engine": eng_path, "propeller": prop_path}
    return {
        "root": str(root),
        "model": "rascal110_e",
        "files": {k: str(v) for k, v in files.items()},
        "sha256": {k: sha256(v) for k, v in files.items()},
        "propeller": prop_info,
    }
